// calculator.net 工具列表配置
const tools = {
  financial: [
    { name: 'Mortgage Calculator', url: '/mortgage-calculator.html', file: 'mortgage_calculator' },
    { name: 'Loan Calculator', url: '/loan-calculator.html', file: 'loan_calculator' },
    { name: 'Auto Loan Calculator', url: '/auto-loan-calculator.html', file: 'auto_loan_calculator' },
    { name: 'Interest Calculator', url: '/interest-calculator.html', file: 'interest_calculator' },
    { name: 'Payment Calculator', url: '/payment-calculator.html', file: 'payment_calculator' },
    { name: 'Retirement Calculator', url: '/retirement-calculator.html', file: 'retirement_calculator' },
    { name: 'Amortization Calculator', url: '/amortization-calculator.html', file: 'amortization_calculator' },
    { name: 'Investment Calculator', url: '/investment-calculator.html', file: 'investment_calculator' },
    { name: 'Currency Calculator', url: '/currency-calculator.html', file: 'currency_calculator' },
    { name: 'Inflation Calculator', url: '/inflation-calculator.html', file: 'inflation_calculator' },
    { name: 'Finance Calculator', url: '/finance-calculator.html', file: 'finance_calculator' },
    { name: 'Mortgage Payoff Calculator', url: '/mortgage-payoff-calculator.html', file: 'mortgage_payoff_calculator' },
    { name: 'Income Tax Calculator', url: '/tax-calculator.html', file: 'income_tax_calculator' },
    { name: 'Compound Interest Calculator', url: '/compound-interest-calculator.html', file: 'compound_interest_calculator' },
    { name: 'Salary Calculator', url: '/salary-calculator.html', file: 'salary_calculator' },
    { name: '401K Calculator', url: '/401k-calculator.html', file: '401k_calculator' },
    { name: 'Interest Rate Calculator', url: '/interest-rate-calculator.html', file: 'interest_rate_calculator' },
    { name: 'Sales Tax Calculator', url: '/sales-tax-calculator.html', file: 'sales_tax_calculator' },
    { name: 'House Affordability Calculator', url: '/house-affordability-calculator.html', file: 'house_affordability_calculator' },
    { name: 'Savings Calculator', url: '/savings-calculator.html', file: 'savings_calculator' },
    { name: 'Rent Calculator', url: '/rent-calculator.html', file: 'rent_calculator' },
    { name: 'Marriage Tax Calculator', url: '/marriage-calculator.html', file: 'marriage_tax_calculator' },
    { name: 'Estate Tax Calculator', url: '/estate-tax-calculator.html', file: 'estate_tax_calculator' },
    { name: 'Pension Calculator', url: '/pension-calculator.html', file: 'pension_calculator' },
    { name: 'Social Security Calculator', url: '/social-security-calculator.html', file: 'social_security_calculator' },
    { name: 'Annuity Calculator', url: '/annuity-calculator.html', file: 'annuity_calculator' },
    { name: 'Annuity Payout Calculator', url: '/annuity-payout-calculator.html', file: 'annuity_payout_calculator' },
    { name: 'Credit Card Calculator', url: '/credit-card-calculator.html', file: 'credit_card_calculator' },
    { name: 'Credit Cards Payoff Calculator', url: '/credit-card-payoff-calculator.html', file: 'credit_card_payoff_calculator' },
    { name: 'Debt Payoff Calculator', url: '/debt-payoff-calculator.html', file: 'debt_payoff_calculator' },
    { name: 'Debt Consolidation Calculator', url: '/debt-consolidation-calculator.html', file: 'debt_consolidation_calculator' },
    { name: 'Repayment Calculator', url: '/repayment-calculator.html', file: 'repayment_calculator' },
    { name: 'Student Loan Calculator', url: '/student-loan-calculator.html', file: 'student_loan_calculator' },
    { name: 'College Cost Calculator', url: '/college-cost-calculator.html', file: 'college_cost_calculator' },
    { name: 'Simple Interest Calculator', url: '/simple-interest-calculator.html', file: 'simple_interest_calculator' },
    { name: 'CD Calculator', url: '/cd-calculator.html', file: 'cd_calculator' },
    { name: 'Bond Calculator', url: '/bond-calculator.html', file: 'bond_calculator' },
    { name: 'Mutual Fund Calculator', url: '/mutual-fund-calculator.html', file: 'mutual_fund_calculator' },
    { name: 'Roth IRA Calculator', url: '/roth-ira-calculator.html', file: 'roth_ira_calculator' },
    { name: 'IRA Calculator', url: '/ira-calculator.html', file: 'ira_calculator' },
    { name: 'RMD Calculator', url: '/rmd-calculator.html', file: 'rmd_calculator' },
    { name: 'VAT Calculator', url: '/vat-calculator.html', file: 'vat_calculator' },
    { name: 'Cash Back or Low Interest Calculator', url: '/cash-back-or-low-interest-calculator.html', file: 'cash_back_low_interest_calculator' },
    { name: 'Auto Lease Calculator', url: '/auto-lease-calculator.html', file: 'auto_lease_calculator' },
    { name: 'Depreciation Calculator', url: '/depreciation-calculator.html', file: 'depreciation_calculator' },
    { name: 'Average Return Calculator', url: '/average-return-calculator.html', file: 'average_return_calculator' },
    { name: 'Margin Calculator', url: '/margin-calculator.html', file: 'margin_calculator' },
    { name: 'Discount Calculator', url: '/discount-calculator.html', file: 'discount_calculator' },
    { name: 'Business Loan Calculator', url: '/business-loan-calculator.html', file: 'business_loan_calculator' },
    { name: 'Debt-to-Income Ratio Calculator', url: '/debt-ratio-calculator.html', file: 'debt_to_income_ratio_calculator' },
    { name: 'Real Estate Calculator', url: '/real-estate-calculator.html', file: 'real_estate_calculator' },
    { name: 'Take-Home-Paycheck Calculator', url: '/take-home-pay-calculator.html', file: 'take_home_paycheck_calculator' },
    { name: 'Personal Loan Calculator', url: '/personal-loan-calculator.html', file: 'personal_loan_calculator' },
    { name: 'Boat Loan Calculator', url: '/boat-loan-calculator.html', file: 'boat_loan_calculator' },
    { name: 'Lease Calculator', url: '/lease-calculator.html', file: 'lease_calculator' },
    { name: 'Refinance Calculator', url: '/refinance-calculator.html', file: 'refinance_calculator' },
    { name: 'Budget Calculator', url: '/budget-calculator.html', file: 'budget_calculator' },
    { name: 'Rental Property Calculator', url: '/rental-property-calculator.html', file: 'rental_property_calculator' },
    { name: 'IRR Calculator', url: '/irr-calculator.html', file: 'irr_calculator' },
    { name: 'ROI Calculator', url: '/roi-calculator.html', file: 'roi_calculator' },
    { name: 'APR Calculator', url: '/apr-calculator.html', file: 'apr_calculator' },
    { name: 'FHA Loan Calculator', url: '/fha-loan-calculator.html', file: 'fha_loan_calculator' },
    { name: 'VA Mortgage Calculator', url: '/va-mortgage-calculator.html', file: 'va_mortgage_calculator' },
    { name: 'Home Equity Loan Calculator', url: '/home-equity-loan-calculator.html', file: 'home_equity_loan_calculator' },
    { name: 'HELOC Calculator', url: '/heloc-calculator.html', file: 'heloc_calculator' },
    { name: 'Down Payment Calculator', url: '/down-payment-calculator.html', file: 'down_payment_calculator' },
    { name: 'Rent vs. Buy Calculator', url: '/rent-vs-buy-calculator.html', file: 'rent_vs_buy_calculator' },
    { name: 'Payback Period Calculator', url: '/payback-period-calculator.html', file: 'payback_period_calculator' },
    { name: 'Present Value Calculator', url: '/present-value-calculator.html', file: 'present_value_calculator' },
    { name: 'Future Value Calculator', url: '/future-value-calculator.html', file: 'future_value_calculator' },
    { name: 'Commission Calculator', url: '/commission-calculator.html', file: 'commission_calculator' },
    { name: 'Mortgage Calculator UK', url: '/mortgage-calculator-uk.html', file: 'mortgage_calculator_uk' },
    { name: 'Canadian Mortgage Calculator', url: '/canadian-mortgage-calculator.html', file: 'canadian_mortgage_calculator' },
    { name: 'Mortgage Amortization Calculator', url: '/mortgage-amortization-calculator.html', file: 'mortgage_amortization_calculator' },
    { name: 'Percent Off Calculator', url: '/percent-off-calculator.html', file: 'percent_off_calculator' }
  ],
  health_fitness: [
    { name: 'BMI Calculator', url: '/bmi-calculator.html', file: 'bmi_calculator' },
    { name: 'Calorie Calculator', url: '/calorie-calculator.html', file: 'calorie_calculator' },
    { name: 'Body Fat Calculator', url: '/body-fat-calculator.html', file: 'body_fat_calculator' },
    { name: 'BMR Calculator', url: '/bmr-calculator.html', file: 'bmr_calculator' },
    { name: 'Macro Calculator', url: '/macro-calculator.html', file: 'macro_calculator' },
    { name: 'Ideal Weight Calculator', url: '/ideal-weight-calculator.html', file: 'ideal_weight_calculator' },
    { name: 'Pregnancy Calculator', url: '/pregnancy-calculator.html', file: 'pregnancy_calculator' },
    { name: 'Pregnancy Weight Gain Calculator', url: '/pregnancy-weight-gain-calculator.html', file: 'pregnancy_weight_gain_calculator' },
    { name: 'Pregnancy Conception Calculator', url: '/pregnancy-conception-calculator.html', file: 'pregnancy_conception_calculator' },
    { name: 'Due Date Calculator', url: '/due-date-calculator.html', file: 'due_date_calculator' },
    { name: 'Pace Calculator', url: '/pace-calculator.html', file: 'pace_calculator' },
    { name: 'Army Body Fat Calculator', url: '/army-body-fat-calculator.html', file: 'army_body_fat_calculator' },
    { name: 'Carbohydrate Calculator', url: '/carbohydrate-calculator.html', file: 'carbohydrate_calculator' },
    { name: 'Lean Body Mass Calculator', url: '/lean-body-mass-calculator.html', file: 'lean_body_mass_calculator' },
    { name: 'Healthy Weight Calculator', url: '/healthy-weight-calculator.html', file: 'healthy_weight_calculator' },
    { name: 'Calories Burned Calculator', url: '/calories-burned-calculator.html', file: 'calories_burned_calculator' },
    { name: 'One Rep Max Calculator', url: '/one-rep-max-calculator.html', file: 'one_rep_max_calculator' },
    { name: 'Target Heart Rate Calculator', url: '/target-heart-rate-calculator.html', file: 'target_heart_rate_calculator' },
    { name: 'Protein Calculator', url: '/protein-calculator.html', file: 'protein_calculator' },
    { name: 'Fat Intake Calculator', url: '/fat-intake-calculator.html', file: 'fat_intake_calculator' },
    { name: 'TDEE Calculator', url: '/tdee-calculator.html', file: 'tdee_calculator' },
    { name: 'Ovulation Calculator', url: '/ovulation-calculator.html', file: 'ovulation_calculator' },
    { name: 'Conception Calculator', url: '/conception-calculator.html', file: 'conception_calculator' },
    { name: 'Period Calculator', url: '/period-calculator.html', file: 'period_calculator' },
    { name: 'GFR Calculator', url: '/gfr-calculator.html', file: 'gfr_calculator' },
    { name: 'Body Type Calculator', url: '/body-type-calculator.html', file: 'body_type_calculator' },
    { name: 'Body Surface Area Calculator', url: '/body-surface-area-calculator.html', file: 'body_surface_area_calculator' },
    { name: 'BAC Calculator', url: '/bac-calculator.html', file: 'bac_calculator' },
    { name: 'Anorexic BMI Calculator', url: '/anorexic-bmi-calculator.html', file: 'anorexic_bmi_calculator' },
    { name: 'Weight Watcher Points Calculator', url: '/weight-watchers-points-calculator.html', file: 'weight_watcher_points_calculator' },
    { name: 'Overweight Calculator', url: '/overweight-calculator.html', file: 'overweight_calculator' }
  ],
  math: [
    { name: 'Scientific Calculator', url: '/scientific-calculator.html', file: 'scientific_calculator' },
    { name: 'Fraction Calculator', url: '/fraction-calculator.html', file: 'fraction_calculator' },
    { name: 'Percentage Calculator', url: '/percent-calculator.html', file: 'percentage_calculator' },
    { name: 'Triangle Calculator', url: '/triangle-calculator.html', file: 'triangle_calculator' },
    { name: 'Volume Calculator', url: '/volume-calculator.html', file: 'volume_calculator' },
    { name: 'Standard Deviation Calculator', url: '/standard-deviation-calculator.html', file: 'standard_deviation_calculator' },
    { name: 'Random Number Generator', url: '/random-number-generator.html', file: 'random_number_generator' },
    { name: 'Number Sequence Calculator', url: '/number-sequence-calculator.html', file: 'number_sequence_calculator' },
    { name: 'Percent Error Calculator', url: '/percent-error-calculator.html', file: 'percent_error_calculator' },
    { name: 'Exponent Calculator', url: '/exponent-calculator.html', file: 'exponent_calculator' },
    { name: 'Binary Calculator', url: '/binary-calculator.html', file: 'binary_calculator' },
    { name: 'Hex Calculator', url: '/hex-calculator.html', file: 'hex_calculator' },
    { name: 'Half-Life Calculator', url: '/half-life-calculator.html', file: 'half_life_calculator' },
    { name: 'Quadratic Formula Calculator', url: '/quadratic-formula-calculator.html', file: 'quadratic_formula_calculator' },
    { name: 'Slope Calculator', url: '/slope-calculator.html', file: 'slope_calculator' },
    { name: 'Log Calculator', url: '/log-calculator.html', file: 'log_calculator' },
    { name: 'Area Calculator', url: '/area-calculator.html', file: 'area_calculator' },
    { name: 'Sample Size Calculator', url: '/sample-size-calculator.html', file: 'sample_size_calculator' },
    { name: 'Probability Calculator', url: '/probability-calculator.html', file: 'probability_calculator' },
    { name: 'Statistics Calculator', url: '/statistics-calculator.html', file: 'statistics_calculator' },
    { name: 'Mean Median Mode Range Calculator', url: '/mean-median-mode-range-calculator.html', file: 'mean_median_mode_range_calculator' },
    { name: 'Permutation and Combination Calculator', url: '/permutation-and-combination-calculator.html', file: 'permutation_combination_calculator' },
    { name: 'Z-score Calculator', url: '/z-score-calculator.html', file: 'z_score_calculator' },
    { name: 'Confidence Interval Calculator', url: '/confidence-interval-calculator.html', file: 'confidence_interval_calculator' },
    { name: 'Ratio Calculator', url: '/ratio-calculator.html', file: 'ratio_calculator' },
    { name: 'Distance Calculator', url: '/distance-calculator.html', file: 'distance_calculator' },
    { name: 'Circle Calculator', url: '/circle-calculator.html', file: 'circle_calculator' },
    { name: 'Surface Area Calculator', url: '/surface-area-calculator.html', file: 'surface_area_calculator' },
    { name: 'Pythagorean Theorem Calculator', url: '/pythagorean-theorem-calculator.html', file: 'pythagorean_theorem_calculator' },
    { name: 'Right Triangle Calculator', url: '/right-triangle-calculator.html', file: 'right_triangle_calculator' },
    { name: 'Root Calculator', url: '/root-calculator.html', file: 'root_calculator' },
    { name: 'Least Common Multiple Calculator', url: '/lcm-calculator.html', file: 'lcm_calculator' },
    { name: 'Greatest Common Factor Calculator', url: '/gcf-calculator.html', file: 'gcf_calculator' },
    { name: 'Factor Calculator', url: '/factor-calculator.html', file: 'factor_calculator' },
    { name: 'Rounding Calculator', url: '/rounding-calculator.html', file: 'rounding_calculator' },
    { name: 'Matrix Calculator', url: '/matrix-calculator.html', file: 'matrix_calculator' },
    { name: 'Scientific Notation Calculator', url: '/scientific-notation-calculator.html', file: 'scientific_notation_calculator' },
    { name: 'Big Number Calculator', url: '/big-number-calculator.html', file: 'big_number_calculator' },
    { name: 'Prime Factorization Calculator', url: '/prime-factorization-calculator.html', file: 'prime_factorization_calculator' },
    { name: 'Common Factor Calculator', url: '/common-factor-calculator.html', file: 'common_factor_calculator' },
    { name: 'Basic Calculator', url: '/basic-calculator.html', file: 'basic_calculator' },
    { name: 'Long Division Calculator', url: '/long-division-calculator.html', file: 'long_division_calculator' },
    { name: 'Average Calculator', url: '/average-calculator.html', file: 'average_calculator' },
    { name: 'P-value Calculator', url: '/p-value-calculator.html', file: 'p_value_calculator' }
  ],
  other: [
    { name: 'Age Calculator', url: '/age-calculator.html', file: 'age_calculator' },
    { name: 'Date Calculator', url: '/date-calculator.html', file: 'date_calculator' },
    { name: 'Time Calculator', url: '/time-calculator.html', file: 'time_calculator' },
    { name: 'Hours Calculator', url: '/hours-calculator.html', file: 'hours_calculator' },
    { name: 'GPA Calculator', url: '/gpa-calculator.html', file: 'gpa_calculator' },
    { name: 'Grade Calculator', url: '/grade-calculator.html', file: 'grade_calculator' },
    { name: 'Height Calculator', url: '/height-calculator.html', file: 'height_calculator' },
    { name: 'Concrete Calculator', url: '/concrete-calculator.html', file: 'concrete_calculator' },
    { name: 'IP Subnet Calculator', url: '/ip-subnet-calculator.html', file: 'ip_subnet_calculator' },
    { name: 'Bra Size Calculator', url: '/bra-size-calculator.html', file: 'bra_size_calculator' },
    { name: 'Password Generator', url: '/password-generator.html', file: 'password_generator' },
    { name: 'Dice Roller', url: '/dice-roller.html', file: 'dice_roller' },
    { name: 'Conversion Calculator', url: '/conversion-calculator.html', file: 'conversion_calculator' },
    { name: 'Fuel Cost Calculator', url: '/fuel-cost-calculator.html', file: 'fuel_cost_calculator' },
    { name: 'Voltage Drop Calculator', url: '/voltage-drop-calculator.html', file: 'voltage_drop_calculator' },
    { name: 'BTU Calculator', url: '/btu-calculator.html', file: 'btu_calculator' },
    { name: 'Square Footage Calculator', url: '/square-footage-calculator.html', file: 'square_footage_calculator' },
    { name: 'Time Card Calculator', url: '/time-card-calculator.html', file: 'time_card_calculator' },
    { name: 'Time Zone Calculator', url: '/time-zone-calculator.html', file: 'time_zone_calculator' },
    { name: 'Love Calculator', url: '/love-calculator.html', file: 'love_calculator' },
    { name: 'GDP Calculator', url: '/gdp-calculator.html', file: 'gdp_calculator' },
    { name: 'Gas Mileage Calculator', url: '/gas-mileage-calculator.html', file: 'gas_mileage_calculator' },
    { name: 'Horsepower Calculator', url: '/horsepower-calculator.html', file: 'horsepower_calculator' },
    { name: 'Engine Horsepower Calculator', url: '/engine-horsepower-calculator.html', file: 'engine_horsepower_calculator' },
    { name: 'Stair Calculator', url: '/stair-calculator.html', file: 'stair_calculator' },
    { name: 'Resistor Calculator', url: '/resistor-calculator.html', file: 'resistor_calculator' },
    { name: 'Ohms Law Calculator', url: '/ohms-law-calculator.html', file: 'ohms_law_calculator' },
    { name: 'Electricity Calculator', url: '/electricity-calculator.html', file: 'electricity_calculator' },
    { name: 'Shoe Size Conversion', url: '/shoe-size-conversion.html', file: 'shoe_size_conversion' },
    { name: 'Tip Calculator', url: '/tip-calculator.html', file: 'tip_calculator' },
    { name: 'Mileage Calculator', url: '/mileage-calculator.html', file: 'mileage_calculator' },
    { name: 'Density Calculator', url: '/density-calculator.html', file: 'density_calculator' },
    { name: 'Mass Calculator', url: '/mass-calculator.html', file: 'mass_calculator' },
    { name: 'Weight Calculator', url: '/weight-calculator.html', file: 'weight_calculator' },
    { name: 'Speed Calculator', url: '/speed-calculator.html', file: 'speed_calculator' },
    { name: 'Molarity Calculator', url: '/molarity-calculator.html', file: 'molarity_calculator' },
    { name: 'Molecular Weight Calculator', url: '/molecular-weight-calculator.html', file: 'molecular_weight_calculator' },
    { name: 'Roman Numeral Converter', url: '/roman-numeral-converter.html', file: 'roman_numeral_converter' },
    { name: 'Golf Handicap Calculator', url: '/golf-handicap-calculator.html', file: 'golf_handicap_calculator' },
    { name: 'Sleep Calculator', url: '/sleep-calculator.html', file: 'sleep_calculator' },
    { name: 'Tire Size Calculator', url: '/tire-size-calculator.html', file: 'tire_size_calculator' },
    { name: 'Roofing Calculator', url: '/roofing-calculator.html', file: 'roofing_calculator' },
    { name: 'Tile Calculator', url: '/tile-calculator.html', file: 'tile_calculator' },
    { name: 'Mulch Calculator', url: '/mulch-calculator.html', file: 'mulch_calculator' },
    { name: 'Gravel Calculator', url: '/gravel-calculator.html', file: 'gravel_calculator' },
    { name: 'Wind Chill Calculator', url: '/wind-chill-calculator.html', file: 'wind_chill_calculator' },
    { name: 'Heat Index Calculator', url: '/heat-index-calculator.html', file: 'heat_index_calculator' },
    { name: 'Dew Point Calculator', url: '/dew-point-calculator.html', file: 'dew_point_calculator' },
    { name: 'Bandwidth Calculator', url: '/bandwidth-calculator.html', file: 'bandwidth_calculator' },
    { name: 'Base64 Encode Decode', url: '/base64-encode-decode.html', file: 'base64_encode_decode' },
    { name: 'URL Encode Decode', url: '/url-encode-decode.html', file: 'url_encode_decode' },
    { name: 'Time Duration Calculator', url: '/time-duration-calculator.html', file: 'time_duration_calculator' },
    { name: 'Day Counter', url: '/day-counter.html', file: 'day_counter' },
    { name: 'Day of the Week Calculator', url: '/day-of-the-week-calculator.html', file: 'day_of_the_week_calculator' }
  ]
};

module.exports = tools;
